DATA:
  data_root: /data/home/dataset/coco2014
  train_list: /data/home/dataset/coco2014/train_data_list.txt 
  val_list: /data/home/dataset/coco2014/val_data_list.txt
  classes: 2  

TRAIN:
  layers: 50
  sync_bn: True
  train_h: 473
  train_w: 473
  scale_min: 0.9  # minimum random scale
  scale_max: 1.1 # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  padding_label: 255
  all_zero_ratio: 0
  aux_weight: 1.0
  train_gpu: [0]
  workers: 8 
  batch_size_val: 1
  start_epoch: 0
  manual_seed: 321
  print_freq: 10
  save_freq: 1
  save_path: exp/coco/split0_5shot/model 
  weight: 
  resume:  # path to latest checkpoint (default: none)
  evaluate: True
  split: 0
  way: 1
  shot: 1
  val_shot: 5
  batch_size: 3 
  lr: 0.0005
  momentum: 0.9
  weight_decay: 0.0005
  lr_milestones: [20000, 40000, 50000] 
  n_steps: 60000 
  use_coco: True
  new_validation: True
  pretrained_path: 
  backbone: 'resnet50'
  epoch_size: 1585 
  test_num: 10000
  only_evaluate: False  

## [Deprecated]
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: False
  world_size: 1
  rank: 0
  use_apex: False
  opt_level: 'O0'
  keep_batchnorm_fp32:
  loss_scale: